### ISSUE TITLE
Create UI for the CrowdAction Info form section.

### ISSUE THREAD

**Issue by dromerolovo** [CollActionteam/collaction_cms#24]
## Subtasks

- [x] Create a shared `TextFormField`.
    * Check `CollActionInputField` widget, should be something similar
- [x] Implement validation logic and error messages.
    * There are some validation function and types `ValueFailures` in Domain that can be used, can be found in `value_validators.dart` and `value_failures.dart`. Also there is a logic to map the values from domain to presentation "displayable" values. Check `MapValidationOutput` class.
- [x] Create a parent widget or intermediary that handle all the fields.
    * This should be the intermediary between all the fields and the widget that binds all the forms sections. 
- [x] Implement calendars for date fields. 
    * A nice package is `syncfusion_flutter_calendar`, extra customization  it's needed in order to follow CollAction styles.
